kmeans:
  init: k-means++
  n_init: 50
  max_iter: 500
  random_state: 42
agglomerative:
  metric: euclidean
  linkage: ward
gmm:
  covariance_type: full
  n_init: 50
  max_iter: 500
  random_state: 42
dbscan:
  eps_range: [0.10, 0.15, 0.20, 0.25, 0.30, 0.40, 0.50, 0.60, 0.80, 1.00]
  min_samples: [3, 4, 5, 10]