data_ingestion:
  root_dir: data/raw
  db_host: localhost
  db_port: 3306
  db_user: root
  db_password: 1234
  db_name: students
  db_table: student_segmentation_data
  raw_data_path: data/raw/raw_student_data.csv

data_validation:
  root_dir: data/validated
  valid_data_path: data/validated/validated_student_data.csv
  report_file_path: data/validated/report.json

data_cleaning:
  root_dir: data/cleaned
  cleaned_data_path: data/cleaned/cleaned_student_data.csv
  report_file_path: data/validated/report.json
  duplicate_strategy: drop
  missing_value_strategy: median
  missing_columns: ['minutes_watched']

feature_engineering:
  root_dir: data/featured
  featured_data_path: data/featured/student_data_features.csv
  log_transform_columns: ['minutes_watched', 'CLV']
  engagement_bins:   [-9999999999, 0, 100, 500, 1500, 9999999999]
  engagement_labels: [0, 1, 2, 3, 4]
  clv_bins: [-9999999999, 0, 62.58, 119.0, 149.99, 9999999999]
  clv_labels: [0, 1, 2, 3, 4]

data_transformation:
  root_dir: data/transformed
  transformed_data_path: data/transformed/transformed_student_data.csv
  scaler: standard
  preprocessor_path: artifacts/preprocessor.pkl
  clustering_features: ["log_minutes", "log_clv"]

model_trainer:
  root_dir: artifacts/models
  metrics_path: artifacts/models/metrics.json
  clustering_features: ["log_minutes_scaled", "log_clv_scaled"]
  max_k: 10

model_evaluator:
  metrics_path: artifacts/models/metrics.json
  weights:
    silhouette_scor: 0.40
    davies_bouldin_score: 0.30
    calinski_harabasz_score: 0.30