data_ingestion:
  root_dir: data/raw
  db_host: localhost
  db_port: 3306
  db_user: root
  db_password: 1234
  db_name: students
  db_table: student_segmentation_data
  raw_data_path: data/raw/raw_student_data.csv

data_validation:
  root_dir: data/validated
  valid_data_path: data/validated/validated_student_data.csv
  report_file_path: data/validated/report.json

data_cleaning:
  root_dir: data/cleaned
  cleaned_data_path: data/cleaned/cleaned_student_data.csv
  duplicate_strategy: drop
  missing_value_strategy: median
  missing_columns: ['minutes_watched']
